In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv("movies_complete.csv")

In [3]:
poster_url = df[["title" ,"poster_path"]]

In [4]:
poster_url.shape

(44691, 2)

In [5]:
movies = pd.read_csv("tmdb_5000_movies.csv")
movies = movies[['title']]

In [6]:
movies
poster_url = movies.merge(poster_url,on="title")

In [7]:
poster_url[poster_url.isna()]==True
for i in poster_url["poster_path"]:
    if i == "NaN":
        print(i)
        break

In [8]:
poster_url[poster_url.isna()]

     title poster_path
0      NaN         NaN
1      NaN         NaN
2      NaN         NaN
3      NaN         NaN
4      NaN         NaN
...    ...         ...
5463   NaN         NaN
5464   NaN         NaN
5465   NaN         NaN
5466   NaN         NaN
5467   NaN         NaN

[5468 rows x 2 columns]

In [9]:
poster_url[poster_url["poster_path"].isnull()]

         title poster_path
3147  The Muse         NaN

In [10]:
poster_url.dropna()

,title,poster_path
0,Avatar,<img src='http://image.tmdb.org/t/p/w185//btnl...
1,Pirates of the Caribbean: At World's End,<img src='http://image.tmdb.org/t/p/w185//oVh3...
2,Spectre,<img src='http://image.tmdb.org/t/p/w185//672k...
3,The Dark Knight Rises,<img src='http://image.tmdb.org/t/p/w185//vzvK...
4,John Carter,<img src='http://image.tmdb.org/t/p/w185//7GSS...
...,...,...
5463,El Mariachi,<img src='http://image.tmdb.org/t/p/w185//zZYP...
5464,Newlyweds,<img src='http://image.tmdb.org/t/p/w185//eINK...
5465,"Signed, Sealed, Delivered",<img src='http://image.tmdb.org/t/p/w185//6BVC...
5466,Shanghai Calling,<img src='http://image.tmdb.org/t/p/w185//2a1q...
5467,My Date with Drew,<img src='http://image.tmdb.org/t/p/w185//19Ch...

In [11]:
import pickle
pickle.dump(poster_url,open("poster_url.pkl", 'wb'))

In [12]:
poster_url["poster_path"][0].split()[1].split()

["src='http://image.tmdb.org/t/p/w185//btnl50ZDJDSCal2NLQIYWw0XxvH.jpg'"]

In [13]:
poster_url["poster_path"][0]

"<img src='http://image.tmdb.org/t/p/w185//btnl50ZDJDSCal2NLQIYWw0XxvH.jpg' style='height:100px;'>"

In [34]:
from bs4 import BeautifulSoup

# # HTML string provided by the user
# html_string = "<img src='http://image.tmdb.org/t/p/w185//btnl50ZDJDSCal2NLQIYWw0XxvH.jpg' style='height:100px;'>"


def html_url(poster_imgs):


    # Parse the HTML
    L = []
    for i in poster_imgs:
        soup = BeautifulSoup(i, 'html.parser')

    # Find the <img> tag
        img_tag = soup.find('img')

    # Extract the URL from the src attribute
        extracted_url = img_tag['src'] if img_tag else None
        L.append(extracted_url)

    return L

In [35]:
poster_url["poster_path"].apply(html_url)

C:\Users\dell\AppData\Local\Temp\ipykernel_10224\3444967580.py:13: MarkupResemblesLocatorWarning: The input looks more like a filename than markup. You may want to open this file and pass the filehandle into Beautiful Soup.
  soup = BeautifulSoup(i, 'html.parser')

TypeError: 'float' object is not iterable

In [15]:
# from bs4 import BeautifulSoup
# import pandas as pd

# def html_url(poster_imgs):
#     # Initialize an empty list to store the extracted URLs
#     L = []
    
#     # Iterate over each item in the list
#     for html_string in poster_imgs:
#         # Ensure the item is a string (HTML string) before processing
#         if isinstance(html_string, str):
#             # Parse the HTML
#             soup = BeautifulSoup(html_string, 'html.parser')
            
#             # Find the <img> tag
#             img_tag = soup.find('img')
            
#             # Extract the URL from the src attribute
#             extracted_url = img_tag['src'] if img_tag else None
            
#             # Append the extracted URL to the list
#             L.append(extracted_url)
#         else:
#             # If the item is not a string, append None or skip
#             L.append(None)
    
#     return L

# # Example usage with a DataFrame
# # poster_urls = poster_url["poster_path"]

# # Assuming poster_url["poster_path"] is a list or pandas Series of HTML strings
# # poster_imgs = 

# # Call the function and get the list of URLs
# urls = html_url(poster_url["poster_path"])

# # Print the extracted URLs
# print(urls)

['http://image.tmdb.org/t/p/w185//btnl50ZDJDSCal2NLQIYWw0XxvH.jpg', 'http://image.tmdb.org/t/p/w185//oVh3REsCwJwmrTkZ9OkkeKiAE02.jpg', 'http://image.tmdb.org/t/p/w185//672kUEMtTHcaVYSVY4eiHEliHFa.jpg', 'http://image.tmdb.org/t/p/w185//vzvKcPQ4o7TjWeGIn0aGC9FeVNu.jpg', 'http://image.tmdb.org/t/p/w185//7GSSyUUgUEXm1rhmiPGSRuKoqnK.jpg', 'http://image.tmdb.org/t/p/w185//rLwhewWypBL88VFGf6haSdnNj2U.jpg', 'http://image.tmdb.org/t/p/w185//1uPxRO0iYwW02lzwatRhkugWBYs.jpg', 'http://image.tmdb.org/t/p/w185//eAfVPfmWbGDhFpRfcLhIj4434SK.jpg', 'http://image.tmdb.org/t/p/w185//4ssDuvEDkSArWEdyBl2X5EHvYKU.jpg', 'http://image.tmdb.org/t/p/w185//Ag21otqbeynZPGjEbzyr3X5Us0j.jpg', 'http://image.tmdb.org/t/p/w185//lQUFeo0oRvtiLKlT5zkQkuCW4jA.jpg', 'http://image.tmdb.org/t/p/w185//6ZYOpyhFZrAQIe1BuhqVgzfAdGZ.jpg', 'http://image.tmdb.org/t/p/w185//f2rCskvSSr7ywPAnFGhk4FT6Piz.jpg', 'http://image.tmdb.org/t/p/w185//AdRQGfT05z6L9gIpUpkh4McMmpm.jpg', 'http://image.tmdb.org/t/p/w185//ffZH45LW2xWAnrjUE5QnvqQqkXK.jpg', 'http://image.tmdb.org/t/p/w185//b2je2ZybNIzAOL1K1WPbbT6zt2M.jpg', 'http://image.tmdb.org/t/p/w185//Atw9fAmRuJzZcZDELbUd1i6g30z.jpg', 'http://image.tmdb.org/t/p/w185//7rIPjn5TUK04O25ZkMyHrGNPgLx.jpg', 'http://image.tmdb.org/t/p/w185//qxz3WIyjZiSKUhaTIEJ3c1GcC9z.jpg', 'http://image.tmdb.org/t/p/w185//1p5thyQ4pCy876HpdvFARqJ62N9.jpg', 'http://image.tmdb.org/t/p/w185//RYMX2wcKCBAr24UyPD7xwmjaTn.jpg', 'http://image.tmdb.org/t/p/w185//keGfSvCmYj7CvdRx36OdVrAEibE.jpg', 'http://image.tmdb.org/t/p/w185//e7kebbtwqzqam6l11aQNl7lXMs0.jpg', 'http://image.tmdb.org/t/p/w185//r4fUzktMexHnTfR3Qn44o3r0XAq.jpg', 'http://image.tmdb.org/t/p/w185//5jsLnOo7kzj7HmAoiJkp1Y5yEgb.jpg', 'http://image.tmdb.org/t/p/w185//84Sa0NvaMLIWpK4zscMhzOiTG78.jpg', 'http://image.tmdb.org/t/p/w185//mdCrp5ubwXhg98AhpgTpgCeQKt8.jpg', 'http://image.tmdb.org/t/p/w185//9NS5QGOfck24yL3bZqWeW06PgPC.jpg', 'http://image.tmdb.org/t/p/w185//rmVyrko5XHRuoO37cRVMOWDm17W.jpg', 'http://image.tmdb.org/t/p/w185//ckAJAtGcIrXy90wUuIdCmLCzkPW.jpg', 'http://image.tmdb.org/t/p/w185//mIHV28g4Zhbc8yhnhOixa8m4p5O.jpg', 'http://image.tmdb.org/t/p/w185//lHlnxKL5GbgRibyRFI7n1Ey850i.jpg', 'http://image.tmdb.org/t/p/w185//paYKhEwUaxKA05vmOfU7FlleTln.jpg', 'http://image.tmdb.org/t/p/w185//qVCZtwBGls866wBb4PAfYtAjyr8.jpg', 'http://image.tmdb.org/t/p/w185//9xjZS2rlVxm8SFx8kPC3aIGCOYQ.jpg', 'http://image.tmdb.org/t/p/w185//22Fh4UoxP6ejL2IFws76TJ8oYlj.jpg', 'http://image.tmdb.org/t/p/w185//AosgVsKPbLctVQ8hd8shEj7LJrZ.jpg', 'http://image.tmdb.org/t/p/w185//tjX3FRx21emmwA30QwXaU39mHoT.jpg', 'http://image.tmdb.org/t/p/w185//mXb3hot6ZW4hMfpZSK7UtD70WgM.jpg', 'http://image.tmdb.org/t/p/w185//rhr4y79GpxQF9IsfJItRXVaoGs4.jpg', 'http://image.tmdb.org/t/p/w185//i3pzXFFLePz5hro9uaVk0E4ZPAO.jpg', 'http://image.tmdb.org/t/p/w185//olxpyq9kJAZ2NU1siLshhhXEPR7.jpg', 'http://image.tmdb.org/t/p/w185//qhPtAc1TKbMPqNvcdXSOn9Bn7hZ.jpg', 'http://image.tmdb.org/t/p/w185//1cbF3s99hCQcFdWG8hrGhKSBles.jpg', 'http://image.tmdb.org/t/p/w185//lOpil36AazWDBaUir5d0AOIhKfd.jpg', 'http://image.tmdb.org/t/p/w185//1jlw8lSaLetDP4XqioTgK6R38Lt.jpg', 'http://image.tmdb.org/t/p/w185//o0kre9wRCZz3jjSjaru7QU0UtFz.jpg', 'http://image.tmdb.org/t/p/w185//vkFhNCUP0W740ARGBrs9xDFvn2Q.jpg', 'http://image.tmdb.org/t/p/w185//9bHz4L3XfZJjHYD6OUa5n6bEeah.jpg', 'http://image.tmdb.org/t/p/w185//r785KH6FBjL0RLvbWAuGgvhbc8c.jpg', 'http://image.tmdb.org/t/p/w185//bAGgcQ5YxFQjmHH52ETkl1Cfqqy.jpg', 'http://image.tmdb.org/t/p/w185//7T9MKqzVRmaPQ2M6GmiIui0a2UC.jpg', 'http://image.tmdb.org/t/p/w185//9JGPYfd8BAXi7eMaDBbqgkyliQq.jpg', 'http://image.tmdb.org/t/p/w185//tyHHjZEzJutWggujN1KP0a1jfLX.jpg', 'http://image.tmdb.org/t/p/w185//6jcxahM7BDAAeKkP4IF8WLFsJ3K.jpg', 'http://image.tmdb.org/t/p/w185//54HFDOswRfShCr25Tvt7JaLiIaf.jpg', 'http://image.tmdb.org/t/p/w185//7lBgN59T5m1DaC9XcLkHOXdK9ax.jpg', 'http://image.tmdb.org/t/p/w185//579HAFLpODEC9Reb64wbCHSUi4O.jpg', 'http://image.tmdb.org/t/p/w185//okpodI7zyPwWsAm2yF5yva6Ea5h.jpg', 'http://image.tmdb.org/t/p/w185//okIz1HyxeVOMzYwwHUjH2pHi74I.jpg', 'http://image.tmdb.org/t/p/w185//fj21HwUprqjjwTdkKC1XZurRSpV.jpg', 'http://image.tmdb.org/t/p/w185//amY0NH1ksd9xJ9boXAMmods6U0D.jpg', 'http://image.tmdb.org/t/p/w185//gw6JhlekZgtKUFlDTezq3j5JEPK.jpg', 'http://image.tmdb.org/t/p/w185//d9jZ2bKZw3ptTuxAyVHA6olPAVs.jpg', 'http://image.tmdb.org/t/p/w185//pLMpv8ckcDP3kiEd2fhwY7XrjHz.jpg', 'http://image.tmdb.org/t/p/w185//vIpDpcF5j3xIx9w6cEzV20SW63S.jpg', 'http://image.tmdb.org/t/p/w185//7XrRkhMa9lQ71RszzSyVrJVvhyS.jpg', 'http://image.tmdb.org/t/p/w185//1xWPdFnrX4v1aCLAA2NHF8w0MGn.jpg', 'http://image.tmdb.org/t/p/w185//qmy6Iz0q5xTCYNFrPvqxx1gw5d7.jpg', 'http://image.tmdb.org/t/p/w185//5fiCMb61u6uRzonRg0duFCh1rKk.jpg', 'http://image.tmdb.org/t/p/w185//nwJbVKauPDgJVQgT7SQpVTVN4gA.jpg', 'http://image.tmdb.org/t/p/w185//3YBcjvU88Q990Ow1fbya29Ph5kb.jpg', 'http://image.tmdb.org/t/p/w185//b0ziG10atX7pJKUpj6XY7C1xSHg.jpg', 'http://image.tmdb.org/t/p/w185//5WClpSPw5v7daTErjmdMeK8T44x.jpg', 'http://image.tmdb.org/t/p/w185//v0VzOKXpJ1hs09beNbVhDo18Slh.jpg', 'http://image.tmdb.org/t/p/w185//56As6XEM1flWvprX4LgkPl8ii4K.jpg', 'http://image.tmdb.org/t/p/w185//8RSkxOO80btfKjyiC5ZiTaCHIT8.jpg', 'http://image.tmdb.org/t/p/w185//8l0pzWBrStFtbZiqeu0cGhxGKkT.jpg', 'http://image.tmdb.org/t/p/w185//vcyL5lBzTtLKPvNng2QcScAAMei.jpg', 'http://image.tmdb.org/t/p/w185//yOnd3XQIg7JBmu0UuBjZyLdsxQD.jpg', 'http://image.tmdb.org/t/p/w185//oMYadKmdsnHaeaMUIdxGICCv9Jb.jpg', 'http://image.tmdb.org/t/p/w185//ajZkWYfg30L9wTzt4p1h8FUB1ZJ.jpg', 'http://image.tmdb.org/t/p/w185//zaqam2RNscH5ooYFWInV6hjx6y5.jpg', 'http://image.tmdb.org/t/p/w185//rJoFwqMaYyS3bmWXQGJh5qa7KMW.jpg', 'http://image.tmdb.org/t/p/w185//m3T3iLdE6J5PrqvvP0XNHBvM2bm.jpg', 'http://image.tmdb.org/t/p/w185//goHDZUnqZJ7FN4h48Qh6MzJNExl.jpg', 'http://image.tmdb.org/t/p/w185//oi1NcVDXlFEsdpLp37BJmFbVlg9.jpg', 'http://image.tmdb.org/t/p/w185//sAqIotgXveaOjNFGd3MCwzCjHat.jpg', 'http://image.tmdb.org/t/p/w185//6empgNd63E1HX8itVf69oDPXVd1.jpg', 'http://image.tmdb.org/t/p/w185//2KMxnbPZilgwF5N1rs6zmpwyVyG.jpg', 'http://image.tmdb.org/t/p/w185//mb4zAOosaO9tHyH1n7g0634moK0.jpg', 'http://image.tmdb.org/t/p/w185//h2QdvfP462FzbmcUHsxKuGACD5T.jpg', 'http://image.tmdb.org/t/p/w185//kzJip9vndXYSKQHCgekrgqbnUrA.jpg', 'http://image.tmdb.org/t/p/w185//qttNmCib9gHhR5q0QoZ3FgmGom9.jpg', 'http://image.tmdb.org/t/p/w185//qJ2tW6WMUDux911r6m7haRef0WH.jpg', 'http://image.tmdb.org/t/p/w185//kq4VZAQy30Hs6kQV4NJk1nZHP50.jpg', 'http://image.tmdb.org/t/p/w185//6MNW96BHtwwWK74d0tLyxVZBkTs.jpg', 'http://image.tmdb.org/t/p/w185//ugfIi08q1LbOnBgsJZFWJy5Gvz4.jpg', 'http://image.tmdb.org/t/p/w185//78lPtwv72eTNqFW9COBYI0dWDJa.jpg', 'http://image.tmdb.org/t/p/w185//2ioR29og3CczWN9lwy8Kxv99351.jpg', 'http://image.tmdb.org/t/p/w185//t5Isp5w4elUOrnXtj11JUdyEMP7.jpg', 'http://image.tmdb.org/t/p/w185//eSYoAGYUygIpnGGd3HyqsvIzgdT.jpg', 'http://image.tmdb.org/t/p/w185//50z0OMn52FtxQDC9EKuO5fcP6oZ.jpg', 'http://image.tmdb.org/t/p/w185//A3acM1lX5PNWQa6r5qeMAJOxbnT.jpg', 'http://image.tmdb.org/t/p/w185//dwr75V4u87yGQwVLWUptnmFK0x8.jpg', 'http://image.tmdb.org/t/p/w185//wcLFe3oPzA4E59D62AORyidmljp.jpg', 'http://image.tmdb.org/t/p/w185//uUHvlkLavotfGsNtosDy8ShsIYF.jpg', 'http://image.tmdb.org/t/p/w185//4L5wGVYPxiYvi3KTWLGqTDQT7Ey.jpg', 'http://image.tmdb.org/t/p/w185//mc9b25IAprHfsaOz0wTshOwGHcY.jpg', 'http://image.tmdb.org/t/p/w185//gVcMbZjXFGi1R3HL8efpkRgz7Zb.jpg', 'http://image.tmdb.org/t/p/w185//lRHE0vzf3oYJrhbsHXjIkF4Tl5A.jpg', 'http://image.tmdb.org/t/p/w185//aLiUq42tjZaQPKOMcwmb7P1xlV0.jpg', 'http://image.tmdb.org/t/p/w185//rYoE6cuup9Ofam6AuYaiJLxF9OO.jpg', 'http://image.tmdb.org/t/p/w185//9YP99QP4D64RKEUs9slPnBWG5lN.jpg', 'http://image.tmdb.org/t/p/w185//tOEOlmLP71IojeJ91dyJ9Nsb8O8.jpg', 'http://image.tmdb.org/t/p/w185//6WBeq4fCfn7AN0o21W9qNcRF2l9.jpg', 'http://image.tmdb.org/t/p/w185//xUNnFwO7XfjvrQ2hFfIlPTwqzDk.jpg', 'http://image.tmdb.org/t/p/w185//ik8PugpL41s137RAWEGTAWu0dPo.jpg', 'http://image.tmdb.org/t/p/w185//nIcZlG4DuAinlEkUzSIEmXy3F5v.jpg', 'http://image.tmdb.org/t/p/w185//5WxZp3XpCnK1EQ6D8XASbpCkrzO.jpg', 'http://image.tmdb.org/t/p/w185//ipsyjW0ciUBffFvI0ZbtiWj7pkv.jpg', 'http://image.tmdb.org/t/p/w185//6esL8UH2sXXqbfbaV6bFEUBCDOr.jpg', 'http://image.tmdb.org/t/p/w185//tRWza39fHyef12FvScIBduaHMi6.jpg', 'http://image.tmdb.org/t/p/w185//xDHnmcroujCRG0ysYQaiswjbyHd.jpg', 'http://image.tmdb.org/t/p/w185//iUXcRneUInxQorD2D8JPdxj9fO8.jpg', 'http://image.tmdb.org/t/p/w185//tVFRpFw3xTedgPGqxW0AOI8Qhh0.jpg', 'http://image.tmdb.org/t/p/w185//6HrfPZtKcGmX2tUWW3cnciZTaSD.jpg', 'http://image.tmdb.org/t/p/w185//jNB2zXgLG8D98X1kYwERVlrW3Oa.jpg', 'http://image.tmdb.org/t/p/w185//xozrGME58olN1xBhtxmjpOoY0jH.jpg', 'http://image.tmdb.org/t/p/w185//j8M1kHBAXa6KFNzGnWtdsVsLUro.jpg', 'http://image.tmdb.org/t/p/w185//vDpziGHmmGZ6Z3OM26751b4y0x6.jpg', 'http://image.tmdb.org/t/p/w185//jzpvh0Ic7jL9GX4NLE1Tx2GUCrN.jpg', 'http://image.tmdb.org/t/p/w185//ygGmAO60t8GyqUo9xYeYxSZAR3b.jpg', 'http://image.tmdb.org/t/p/w185//jdG3l2e7kJ4bl91YLRLUAmvbZMX.jpg', 'http://image.tmdb.org/t/p/w185//r7vmZjiyZw9rpJMQJdXpjgiCOk9.jpg', 'http://image.tmdb.org/t/p/w185//gEU2QniE6E77NI6lCU6MxlNBvIx.jpg', 'http://image.tmdb.org/t/p/w185//9gk7adHYeDvHkCSEqAvQNLV5Uge.jpg', 'http://image.tmdb.org/t/p/w185//jPNShaWZMpVF0iQ7j1dvTuZLD20.jpg', 'http://image.tmdb.org/t/p/w185//qQeVJAvx6YCRGqaaZZpPm1WxMv6.jpg', 'http://image.tmdb.org/t/p/w185//5En3O5t9LG8PfRaNs3vKfMdjQ1B.jpg', 'http://image.tmdb.org/t/p/w185//tm9vnOW6QY2dJo67iw1q2B4fs6y.jpg', 'http://image.tmdb.org/t/p/w185//9H2awZmNisMVJGp362Stv0bfUTs.jpg', 'http://image.tmdb.org/t/p/w185//yoKdvhqVw45oEF34No2cD7aP3sx.jpg', 'http://image.tmdb.org/t/p/w185//lImKHDfExAulp16grYm8zD5eONE.jpg', 'http://image.tmdb.org/t/p/w185//qC4i8fj4IpkOHUFQ1Lg85hiIF5B.jpg', 'http://image.tmdb.org/t/p/w185//fzedrpmGwqAwkDsJqnyIaq4FXLQ.jpg', 'http://image.tmdb.org/t/p/w185//cCx2Ead8KoZhHofsAAr7tyrjfDo.jpg', 'http://image.tmdb.org/t/p/w185//apIIYMOhUvamblS8ftoNf6nZqUt.jpg', 'http://image.tmdb.org/t/p/w185//uGsjYHPZ0NbI7GHrHlq98D4kFYB.jpg', 'http://image.tmdb.org/t/p/w185//iWCWbYqPGyNIHcA8wZ9zsGCugcp.jpg', 'http://image.tmdb.org/t/p/w185//k3a41SS1q5xmbvzPvzTIfG7GDlp.jpg', 'http://image.tmdb.org/t/p/w185//oZRVDpNtmHk8M1VYy1aeOWUXgbC.jpg', 'http://image.tmdb.org/t/p/w185//pP27zlm9yeKrCeDZLFLP2HKELot.jpg', 'http://image.tmdb.org/t/p/w185//kVzdU4SmgUpBh1k5vofpARKgo6h.jpg', 'http://image.tmdb.org/t/p/w185//oz7WsSLalkh60q1e0uzqqpbaB2g.jpg', 'http://image.tmdb.org/t/p/w185//89yaPwgX4YvHzDuykMKyItRgz5l.jpg', 'http://image.tmdb.org/t/p/w185//g6n8G0xPnBVUIKKK41sNmbZB5h4.jpg', 'http://image.tmdb.org/t/p/w185//fECBtHlr0RB3foNHDiCBXeg9Bv9.jpg', 'http://image.tmdb.org/t/p/w185//7DyuV2G0hLEqHeueDfOqhZ2DVut.jpg', 'http://image.tmdb.org/t/p/w185//iPDkaSdKk2jRLTM65UOEoKtsIZ8.jpg', 'http://image.tmdb.org/t/p/w185//Oop38B7iJdykEkpAhNZKbEz91t.jpg', 'http://image.tmdb.org/t/p/w185//npHNjldbeTHdKKw28bJKs7lzqzj.jpg', 'http://image.tmdb.org/t/p/w185//aGdng8Ic4ONpcepU3bVXPSLmNd3.jpg', 'http://image.tmdb.org/t/p/w185//agRbLOHgN46TQO4YdKR462iR7To.jpg', 'http://image.tmdb.org/t/p/w185//rBm8YJUH1Sh0yGn2w5MEjOhwP3F.jpg', 'http://image.tmdb.org/t/p/w185//mQglrQzgZT0Oj9cQYPsLI8dsEqB.jpg', 'http://image.tmdb.org/t/p/w185//cm14gG8xBghwIAy1GX0ryI2HA4U.jpg', 'http://image.tmdb.org/t/p/w185//6SjRpaJg43iJnY0jlJ6c61tAKOo.jpg', 'http://image.tmdb.org/t/p/w185//zhJAHdhjSazDiOrVwOgfhHCLqI8.jpg', 'http://image.tmdb.org/t/p/w185//yald8Lsb4uCRvjIH3spzR84Kdwf.jpg', 'http://image.tmdb.org/t/p/w185//8xEVAe84zlL9rkfYT6dZXero4KK.jpg', 'http://image.tmdb.org/t/p/w185//54s3EKPVP4uIvKX4hj5X23ZbNYB.jpg', 'http://image.tmdb.org/t/p/w185//sQuxceRcV3cxKH5CAnAUZe0qFKS.jpg', 'http://image.tmdb.org/t/p/w185//uRBapeuwV8yy4in4BkETHBDmWkH.jpg', 'http://image.tmdb.org/t/p/w185//prSfAi1xGrhLQNxVSUFh61xQ4Qy.jpg', 'http://image.tmdb.org/t/p/w185//z9VHoUcZ1GiH3f3qYz7Me7Zc1Fd.jpg', 'http://image.tmdb.org/t/p/w185//jpjG88kTrK7mHnRx4cpLHh8YZwr.jpg', 'http://image.tmdb.org/t/p/w185//5HLqkUr7WJkcjdYXvjwjUSuIWCD.jpg', 'http://image.tmdb.org/t/p/w185//fd9Ck4cxVlmtXsbeGtQW7WFuUFI.jpg', 'http://image.tmdb.org/t/p/w185//dTuAIC7a7ncN4uEHtzjumLB7jje.jpg', 'http://image.tmdb.org/t/p/w185//a5DTeWNPQoUfjB7L2zgW02zuFdK.jpg', 'http://image.tmdb.org/t/p/w185//rYBaXgvTKFS8iZC7Wr8SMomSauQ.jpg', 'http://image.tmdb.org/t/p/w185//mtqqD00vB4PGRt20gWtGqFhrkd0.jpg', 'http://image.tmdb.org/t/p/w185//zgwRTYWEEPivTwjB9S03HtmMcbM.jpg', 'http://image.tmdb.org/t/p/w185//uXThDsEdXfepDiDlsIvuUQJ82bl.jpg', 'http://image.tmdb.org/t/p/w185//mcHPUtO3HnssUQ1OYP6w3FiDXYs.jpg', 'http://image.tmdb.org/t/p/w185//lOKqLd0ud1wdwaPK5h6bGNZIVLT.jpg', 'http://image.tmdb.org/t/p/w185//885fQK8aQw8sQiQVco9ffQZvJ9t.jpg', 'http://image.tmdb.org/t/p/w185//byzDFq0kerun9iC9EhQ0D4FpvJN.jpg', 'http://image.tmdb.org/t/p/w185//mYc7P87ZGpV9vZyX27LKIXPeMig.jpg', 'http://image.tmdb.org/t/p/w185//zfM3kcF6IiHkM84JsMFYAnKnEuh.jpg', 'http://image.tmdb.org/t/p/w185//kWj4RJzZeJGeyGA3DVGQiNkUjkt.jpg', 'http://image.tmdb.org/t/p/w185//ekraj4ksvIKeuvQVEevEJkuybZd.jpg', 'http://image.tmdb.org/t/p/w185//bZmGqOhMhaLn8AoFMvFDct4tbrL.jpg', 'http://image.tmdb.org/t/p/w185//h5Qz8J4T8YQnbZzHXM73WVYYVPK.jpg', 'http://image.tmdb.org/t/p/w185//bqtB8yylZEcpfOPox4HA4IL2bXG.jpg', 'http://image.tmdb.org/t/p/w185//fMtOCd0EAdAzKtGLQiHjSUvbdNc.jpg', 'http://image.tmdb.org/t/p/w185//dSUScgxwOOIVDTvqSM9xbhb1g4X.jpg', 'http://image.tmdb.org/t/p/w185//yixY91cdFeNbW2YPPjxeqwX6sUM.jpg', 'http://image.tmdb.org/t/p/w185//enA22EPyzc2WQ1VVyY7zxresQQr.jpg', 'http://image.tmdb.org/t/p/w185//ajNUvzgzSYb4JKcfjcCgJl1r5dH.jpg', 'http://image.tmdb.org/t/p/w185//gJQswntB4Knt3a2H8PDyat8T6SY.jpg', 'http://image.tmdb.org/t/p/w185//nlr2oxuYsHXt0wdtmzaOuVBoNC0.jpg', 'http://image.tmdb.org/t/p/w185//khlcsYHr7Hi4Tkymc7UGDvcUcx.jpg', 'http://image.tmdb.org/t/p/w185//kUBkmlWriPbNMijL2m3LtmPYPTb.jpg', 'http://image.tmdb.org/t/p/w185//6NpHoon3PVKaoghpnRqJVBIbAvf.jpg', 'http://image.tmdb.org/t/p/w185//1NBVGBi8Z6MhJBAJ5SuRMqP7o3T.jpg', 'http://image.tmdb.org/t/p/w185//wwCOJtRAkn287NbWUtOTlYbiL4Z.jpg', 'http://image.tmdb.org/t/p/w185//8TSSBdw1CiIWZkWmcALoLdWs4Do.jpg', 'http://image.tmdb.org/t/p/w185//hN2ZtF3Uw6mhIHZiqL0SKzELtKn.jpg', 'http://image.tmdb.org/t/p/w185//vSsOo0GwXP2zDZP4EyXmHejJ3H8.jpg', 'http://image.tmdb.org/t/p/w185//d13Uj86LdbDLrfDoHR5aDOFYyJC.jpg', 'http://image.tmdb.org/t/p/w185//zpXkim56DyQIbZPpMyTqygo81Kc.jpg', 'http://image.tmdb.org/t/p/w185//gNoEWBl5vCTwbzOt7sFpZsuIZjf.jpg', 'http://image.tmdb.org/t/p/w185//aZvOkdo203bm1kpcY0A0Tn074ER.jpg', 'http://image.tmdb.org/t/p/w185//qc0GVMhZk44icQdynIin0xkE9YZ.jpg', 'http://image.tmdb.org/t/p/w185//ycxWyYm5li51say11DJziMaCZMz.jpg', 'http://image.tmdb.org/t/p/w185//3rWIZMzTKcCtV0eHJ70Z4Ru659f.jpg', 'http://image.tmdb.org/t/p/w185//roVIPqVLMdvs7uOcqDuwO891t8s.jpg', 'http://image.tmdb.org/t/p/w185//kyY1onYxkKBDlJsheRsVbMaoQEM.jpg', 'http://image.tmdb.org/t/p/w185//oX3kz2EXPIm4GcxaOShVaH2Jyny.jpg', 'http://image.tmdb.org/t/p/w185//9p8SQYNazWavpMzhN0OIuZm0HgI.jpg', 'http://image.tmdb.org/t/p/w185//yAciM4Qcg5CIuXMUI7Ew5uLS4WB.jpg', 'http://image.tmdb.org/t/p/w185//vSNxAJTlD0r02V9sPYpOjqDZXUK.jpg', 'http://image.tmdb.org/t/p/w185//bc1MIdWr8Y9RsfD9Qq7932prh5v.jpg', 'http://image.tmdb.org/t/p/w185//s1cVTQEZYn4nSjZLnFbzLP0j8y2.jpg', 'http://image.tmdb.org/t/p/w185//jHE7WUf3FDod8vw3O3twh0JVZun.jpg', 'http://image.tmdb.org/t/p/w185//2gWiQ4mn85jcXtREVePlVViupeV.jpg', 'http://image.tmdb.org/t/p/w185//vcFeElC8eXI668WSIxcDNkJSBxv.jpg', 'http://image.tmdb.org/t/p/w185//4zawxGJIH43DcoGG9Ui0WoIcrQC.jpg', 'http://image.tmdb.org/t/p/w185//bECzzYkRFlCZZAjQ9wboMGyWFcL.jpg', 'http://image.tmdb.org/t/p/w185//tSaBkriE7TpbjFoQUFXuikoz0dF.jpg', 'http://image.tmdb.org/t/p/w185//lDARMqluCrWaFgybY9KHLY96L3n.jpg', 'http://image.tmdb.org/t/p/w185//fK60JeK00vkRTi2vVp3vxzsBli6.jpg', 'http://image.tmdb.org/t/p/w185//gbtwoYMWlG0HZe7sDaTOoijtXCu.jpg', 'http://image.tmdb.org/t/p/w185//d4DuphCHCjVUyffExnK5nLbn39K.jpg', 'http://image.tmdb.org/t/p/w185//wWt4JYXTg5Wr3xBW2phBrMKgp3x.jpg', 'http://image.tmdb.org/t/p/w185//fddtVEUozxvLmehR5yGZjem44pD.jpg', 'http://image.tmdb.org/t/p/w185//7c1JtraYsjMMnk8Md0IMoyRzqZJ.jpg', 'http://image.tmdb.org/t/p/w185//4RT9qiWzHe880FnVH5RtxDAobFs.jpg', 'http://image.tmdb.org/t/p/w185//pNGfPhVo9CVFkwuvahzITvKhe0r.jpg', 'http://image.tmdb.org/t/p/w185//b7czgMTk5txqLr2UczBb0Wez77E.jpg', 'http://image.tmdb.org/t/p/w185//hj9XSUzW1jsd09xQ4IyHpTLpj6V.jpg', 'http://image.tmdb.org/t/p/w185//iSnRfGxEeX9O2rTHcWn38qR5D1F.jpg', 'http://image.tmdb.org/t/p/w185//caq7SUZwXkESWYoQMGVb4byXbuQ.jpg', 'http://image.tmdb.org/t/p/w185//6Biy7R9LfumYshur3YKhpj56MpB.jpg', 'http://image.tmdb.org/t/p/w185//yCvB5fG5aEPqa1St7ihY6KEAsHD.jpg', 'http://image.tmdb.org/t/p/w185//ppXyhOe8UCEOrBRSYqE3SkHwrcR.jpg', 'http://image.tmdb.org/t/p/w185//g4O8tCuWXl33dppjPSxj472B9sI.jpg', 'http://image.tmdb.org/t/p/w185//b7QgQbFs3IC9BxJKZeNyJ6QYul3.jpg', 'http://image.tmdb.org/t/p/w185//iXzfrdOYh0XmdjREIrZuU8sGHg6.jpg', 'http://image.tmdb.org/t/p/w185//uDQibffYgssdiqx7izO57wdLc6.jpg', 'http://image.tmdb.org/t/p/w185//45X7LFsgYvdEgFCkXSZCQOZMuJX.jpg', 'http://image.tmdb.org/t/p/w185//kteClJzPpygDW40xyICWfzmYTIW.jpg', 'http://image.tmdb.org/t/p/w185//rSje3FS7ycJSglowlngjsvDt7vO.jpg', 'http://image.tmdb.org/t/p/w185//ipZlg4EVo4kj2TjiR0hfSYdEzbd.jpg', 'http://image.tmdb.org/t/p/w185//ozecjGWL47TQ9mKrPg2Y3WTh2UJ.jpg', 'http://image.tmdb.org/t/p/w185//wuMc08IPKEatf9rnMNXvIDxqP4W.jpg', 'http://image.tmdb.org/t/p/w185//fQ7CI5zmmhZlHuYBFKgK9w4hwlS.jpg', 'http://image.tmdb.org/t/p/w185//z8onk7LV9Mmw6zKz4hT6pzzvmvl.jpg', 'http://image.tmdb.org/t/p/w185//4FAA18ZIja70d1Tu5hr5cj2q1sB.jpg', 'http://image.tmdb.org/t/p/w185//6jexEWBXepwB1ZLpCEllI04Agrb.jpg', 'http://image.tmdb.org/t/p/w185//urFzh1shUnJCzc6eI7MqV4RsJWP.jpg', 'http://image.tmdb.org/t/p/w185//r3i3rMSHneAp9uQNZA4I04y9S4p.jpg', 'http://image.tmdb.org/t/p/w185//qwzPdODt6nwZ9VjXEf3QYRmFULl.jpg', 'http://image.tmdb.org/t/p/w185//y1MYZkwhZK6L0Jy4YMuPktzDOfn.jpg', 'http://image.tmdb.org/t/p/w185//i17T4vln1OYC3TD4glwfRoqZm1E.jpg', 'http://image.tmdb.org/t/p/w185//nzaolaRSo8ZIGjxnX89PEnpROae.jpg', 'http://image.tmdb.org/t/p/w185//6sBC42cv4EsqsIIEJQs1yadnSXK.jpg', 'http://image.tmdb.org/t/p/w185//fucmGeZYM4yzqJUnDTc4pKQNCej.jpg', 'http://image.tmdb.org/t/p/w185//7pyhR5K1iv67daYw0DfsmsersKA.jpg', 'http://image.tmdb.org/t/p/w185//ucqtAussxYNRw4lGvRaSbRJLskV.jpg', 'http://image.tmdb.org/t/p/w185//bsg0mrxUKyJoL4oSGP5mlhEsqp.jpg', 'http://image.tmdb.org/t/p/w185//qYYIxgm9qxz1Fvu6mA6gKs9iLZC.jpg', 'http://image.tmdb.org/t/p/w185//zf68Es2NLQ33ZzSYYtcSn6HMiRR.jpg', 'http://image.tmdb.org/t/p/w185//12mI7kU22nJrmtAgGcDP8tbAz4a.jpg', 'http://image.tmdb.org/t/p/w185//aOYHJclz1yZdFT3hdMY8TeYU4fk.jpg', 'http://image.tmdb.org/t/p/w185//d2zSsh1jqhrIzWEk1UZyRudoTx9.jpg', 'http://image.tmdb.org/t/p/w185//mYDKm9HxImm8PRru3KbkHAe1cmk.jpg', 'http://image.tmdb.org/t/p/w185//1pyU94dAY7npDQCKuxCSyX9KthN.jpg', 'http://image.tmdb.org/t/p/w185//xA7N41glw17MBQtcWSm2eBlBRuG.jpg', 'http://image.tmdb.org/t/p/w185//n4cdJ0Wqxb7C0HmZbcaC4eYnkIf.jpg', 'http://image.tmdb.org/t/p/w185//qsYQflQhOuhDpQ0W2aOcwqgDAeI.jpg', 'http://image.tmdb.org/t/p/w185//hjfeMLWqJY44mqqJKZSa6jx4Y1j.jpg', 'http://image.tmdb.org/t/p/w185//6hVMt55kzUHvxnc5lduqXyMh8VP.jpg', 'http://image.tmdb.org/t/p/w185//hqElSkdQBTkNBcVQRUemcT4yRQT.jpg', 'http://image.tmdb.org/t/p/w185//o8XtRKAg4DUSOhYofyAoUWa9PhK.jpg', 'http://image.tmdb.org/t/p/w185//gM5ql3BKYmHG3WtZ0buKXN7xY8O.jpg', 'http://image.tmdb.org/t/p/w185//yQkxpeWeLRFQ5mKMPXqYHjITOE.jpg', 'http://image.tmdb.org/t/p/w185//zA2duSy0zk0VAB88x2jygu6o2e5.jpg', 'http://image.tmdb.org/t/p/w185//a7JmOBMNj5erYTgt4u1mQgvHItu.jpg', 'http://image.tmdb.org/t/p/w185//2ncs7hqBsEjFMqt6Y7ShBCO9tWs.jpg', 'http://image.tmdb.org/t/p/w185//ndh5b1EmH9233Jbvs2sy8OXrZkS.jpg', 'http://image.tmdb.org/t/p/w185//iXm2KPqASpRg8fnsP7cVO6HLiJ3.jpg', 'http://image.tmdb.org/t/p/w185//8kGTtqWat7mXnotom39KzfBeS3m.jpg', 'http://image.tmdb.org/t/p/w185//oZNPzxqM2s5DyVWab09NTQScDQt.jpg', 'http://image.tmdb.org/t/p/w185//8hMd1BIcCwISqxOdo1G4UXCEOI.jpg', 'http://image.tmdb.org/t/p/w185//fvNIRADfDNihVNWx2JvBsaPYUow.jpg', 'http://image.tmdb.org/t/p/w185//6wkfovp

In [17]:

poster_url[["poster_path"]][0:2]

                                         poster_path
0  <img src='http://image.tmdb.org/t/p/w185//btnl...
1  <img src='http://image.tmdb.org/t/p/w185//oVh3...

In [30]:
# L = []
# for i in poster_url["poster_path"][0:2]:
#     print(i)
#     soup = BeautifulSoup(i, 'html.parser')

#     # Find the <img> tag
#     img_tag = soup.find('img')

#     # Extract the URL from the src attribute
#     extracted_url = img_tag['src'] if img_tag else None
#     L.append(extracted_url)

# print(L)

<img src='http://image.tmdb.org/t/p/w185//btnl50ZDJDSCal2NLQIYWw0XxvH.jpg' style='height:100px;'>
<img src='http://image.tmdb.org/t/p/w185//oVh3REsCwJwmrTkZ9OkkeKiAE02.jpg' style='height:100px;'>
['http://image.tmdb.org/t/p/w185//btnl50ZDJDSCal2NLQIYWw0XxvH.jpg', 'http://image.tmdb.org/t/p/w185//oVh3REsCwJwmrTkZ9OkkeKiAE02.jpg']

In [29]:
# # Parse the HTML
# L = []
# for i in poster_imgs:
#     soup = BeautifulSoup(i, 'html.parser')

# # Find the <img> tag
#     img_tag = soup.find('img')

# # Extract the URL from the src attribute
#     extracted_url = img_tag['src'] if img_tag else None
#     L.append(extracted_url)

# print(L)